viur-framework/viur-shop

- src/viur/shop/skeletons/cart.py
- src/viur/shop/types/price.py
This PR fix the problem that if you select the `application_domain` Basket the Discount was set on all Article in the Basket
> fix: Calculation of discount for baskets

- src/viur/shop/data/translations.py
- src/viur/shop/modules/order.py
- src/viur/shop/payment_providers/__init__.py
- src/viur/shop/payment_providers/abstract.py
- src/viur/shop/payment_providers/amazon_pay.py
- src/viur/shop/payment_providers/prepayment.py
- src/viur/shop/payment_providers/unzer_abstract.py
- src/viur/shop/skeletons/order.py
Add Prepayment Provider.
Add `image_path` and `description` for the Frontend.
> feat: Add Prepayment Provider

- pyproject.toml
- src/viur/shop/data/translations.py
- src/viur/shop/payment_providers/__init__.py
- src/viur/shop/payment_providers/unzer_bancontact.py
- Implement `UnzerBancontact`
- Add imports
> feat: Implement more Unzer payment providers

- src/viur/shop/modules/address.py
- src/viur/shop/modules/order.py
- src/viur/shop/payment_providers/abstract.py
- src/viur/shop/payment_providers/unzer_abstract.py
- src/viur/shop/skeletons/order.py
- src/viur/shop/types/__init__.py
- src/viur/shop/types/results.py
Allows to allow payment provider only in specific languages, or for a few users, ...
> feat: Filter for available payment provider

- src/viur/shop/modules/address.py
- src/viur/shop/modules/cart.py
- src/viur/shop/modules/order.py
- src/viur/shop/skeletons/address.py
This should simplify the frontend as you can use the same object for billing as shipping
Decided together with @akelch
> feat: Make `address_type` multiple

- src/viur/shop/modules/api.py
- src/viur/shop/modules/order.py
- src/viur/shop/payment_providers/__init__.py
- src/viur/shop/payment_providers/abstract.py
- src/viur/shop/payment_providers/amazon_pay.py
- src/viur/shop/payment_providers/invoice.py
- src/viur/shop/payment_providers/paypal_plus.py
- src/viur/shop/payment_providers/unzer_abstract.py
- src/viur/shop/payment_providers/unzer_bancontact.py
- src/viur/shop/payment_providers/unzer_card.py
- src/viur/shop/payment_providers/unzer_ideal.py
- src/viur/shop/payment_providers/unzer_paypal.py
- src/viur/shop/payment_providers/unzer_sofort.py
- src/viur/shop/skeletons/order.py
- src/viur/shop/types/exceptions.py
And do some more or less related fixes + refactorings
> feat: Implement `PaymentProvider` `Invoice` and complete `Prepayment`

- src/viur/shop/modules/vat_rate.py
> feat(performance): Cache vat for country

- src/viur/shop/modules/api.py
- src/viur/shop/modules/cart.py
- src/viur/shop/modules/order.py
And
* Improve `Cart.canView`
* Implement `Cart.cart_get`
> fix: Make `Api.basket_view` working for guests

- src/viur/shop/modules/order.py
and chore: Add order for admin
> feat: Add missing billing_address and email validation

- src/viur/shop/data/translations.py
- src/viur/shop/modules/api.py
- src/viur/shop/modules/order.py
- src/viur/shop/skeletons/order.py
- src/viur/shop/types/data.py
> feat: Implement `phone` bone in `OrderSkel`

- src/viur/shop/skeletons/cart.py
- src/viur/shop/skeletons/order.py
- src/viur/shop/skeletons/vat.py
- src/viur/shop/types/price.py
* Include shipping cost in cart total and cart vat
* Correct vat calculation and implement helper method
* Introduce generic `Addititon`s as more flexible solution than subclassing `TotalFactory`
> fix: Price Calculation

- src/viur/shop/skeletons/cart.py
- src/viur/shop/skeletons/order.py
Use correct module name for cart relation in order
> fix: Correct modules of `RelationalBones` in `CartNodeSkel` and `OrderSkel`

- src/viur/shop/modules/abstract.py
- src/viur/shop/shop.py
* Remove `register` loop from `shop` reference in modules
* Create a new renderer instance for this module
> fix: Get renderer working as expected

- src/viur/shop/skeletons/address.py
- src/viur/shop/skeletons/article.py
- src/viur/shop/skeletons/cart.py
- src/viur/shop/skeletons/discount.py
- src/viur/shop/skeletons/discount_condition.py
- src/viur/shop/skeletons/order.py
- src/viur/shop/skeletons/shipping.py
- src/viur/shop/skeletons/shipping_config.py
- src/viur/shop/skeletons/vat.py
- src/viur/shop/skeletons/vat_rate.py
> feat: Make a bunch of bones searchable

- pyproject.toml
- src/viur/shop/modules/discount.py
- src/viur/shop/modules/discount_condition.py
This is more simple than using hacks with `functools`' `lru_cache`
> feat: Use `cachetools` for caching of methods

- src/viur/shop/modules/discount.py
- src/viur/shop/skeletons/discount_condition.py
- src/viur/shop/types/dc_scope.py
* language, country and article scope bones are now multiple
* Define vFunc for code validation
* Adjust discount validators
> feat: Make some discount scopes multiple

- src/viur/shop/modules/order.py
maybe a bug, transaction conflict, ... needs more time ...
> fix: Refresh order, cart.shipping_address relation seems not be updated

- src/viur/shop/modules/cart.py
> fix: Do not delete a cart in `delete_guest_cart` if it is used by an order

- src/viur/shop/modules/address.py
- src/viur/shop/modules/cart.py
- src/viur/shop/modules/discount.py
- src/viur/shop/modules/discount_condition.py
- src/viur/shop/modules/order.py
- src/viur/shop/skeletons/cart.py
* Add `is_frozen`, `frozen_values`, and `article_cache` to `CartNodeSkel` and `CartItemSkel`
* Refactor article copying, recursive leaf/node freezing with `freeze_cart`/`freeze_leaf`
* Refactor to `clone_address` helper
> feat: Extend order & cart freeze processing

- src/viur/shop/modules/discount_condition.py
and modify skel in `canEdit` only if it's clones (not the case / not nessary for clone)
> fix: Implement clone methods in module `DiscountConditon`

- src/viur/shop/modules/api.py
- src/viur/shop/modules/cart.py
- src/viur/shop/modules/discount.py
- src/viur/shop/types/__init__.py
- src/viur/shop/types/dc_scope.py
- src/viur/shop/types/exceptions.py
* Improve Error Handling; Use HTTP errors
* Change `scope_article` to generic validation
* Add missing / Improve existing documentation
* Disable debug logs
> fix: Improve discount codes

- src/viur/shop/modules/cart.py
Don't clone the address if there isn't one
> fix: `freeze_cart`; sub-carts might have no own shipping
